services:
  - type: web
    name: documind-frontend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    rootDir: client
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_API_URL
        sync: false
    healthCheckPath: /health
