services:
  - type: web
    name: documind-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    rootDir: server
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: QDRANT_HOST
        sync: false
      - key: QDRANT_PORT
        value: 6333
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        value: documents
      - key: OPENAI_API_KEY
        sync: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: uploads
      - key: LOG_LEVEL
        value: info
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
